=== Marci-2/Q25EP3WebXML/DomParseQ25EP3/src/Q25EP3_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="csillagType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cimType">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gyakorlatType">
        <xs:sequence>
            <xs:element name="kezdete" type="xs:string"/>
            <xs:element name="idotartama" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:positiveInteger"/>
            <xs:element name="vegzettsev" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="szakacsType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="reszleg" type="xs:string"/>
            <xs:element name="vegzettsev" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="gyakornokType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="gyakorlat" type="gyakorlatType"/>
            <xs:element name="muszak" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="vendegType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:positiveInteger"/>
            <xs:element name="cim" type="cimType"/>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesType">
        <xs:sequence>
            <xs:element name="osszeg" type="xs:positiveInteger"/>
            <xs:element name="etel" type="xs:string"/>
            <xs:element name="vendeg" type="vendegType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="etteremType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="csillag" type="csillagType"/>
            <xs:element name="cim" type="cimType"/>
            <xs:element name="foszakacs" type="foszakacsType"/>
            <xs:element name="szakacs" type="szakacsType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="gyakornok" type="gyakornokType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="rendeles" type="rendelesType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ekod" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:element name="LM_etterem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="etterem" type="etteremType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Marci-2/Q25EP3WebXML/DomParseQ25EP3/src/q25ep3/Q25EP3_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<LM_etterem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="Q25EP3_XMLSchema.xsd">

    <etterem ekod="e1">
        <nev>LM Étterem</nev>
        <csillag>5</csillag>
        <cim>
            <varos>Miskolc</varos>
            <utca>Egyetem út</utca>
            <hazszam>1</hazszam>
        </cim>

        <foszakacs fkod="f1">
            <nev>Nagy Péter</nev>
            <eletkor>42</eletkor>
            <vegzettsev>Mester szakács</vegzettsev>
            <vegzettsev>Élelmiszermérnök</vegzettsev>
        </foszakacs>

        <szakacs szkod="sz1">
            <nev>Kovács István</nev>
            <reszleg>Melegkonyha</reszleg>
            <vegzettsev>Szakács szakképesítés</vegzettsev>
        </szakacs>

        <gyakornok gykod="gy1">
            <nev>Tóth Anna</nev>
            <gyakorlat>
                <kezdete>2026-02-01</kezdete>
                <idotartama>6 hónap</idotartama>
            </gyakorlat>
            <muszak>délelőtt</muszak>
            <muszak>délután</muszak>
        </gyakornok>

        <rendeles>
            <osszeg>12500</osszeg>
            <etel>Bécsi szelet</etel>
            <vendeg vkod="v1">
                <nev>Szabó Gábor</nev>
                <eletkor>30</eletkor>
                <cim>
                    <varos>Miskolc</varos>
                    <utca>Fő utca</utca>
                    <hazszam>12</hazszam>
                </cim>
            </vendeg>
        </rendeles>
    </etterem>

</LM_etterem>
